name: Upload video to Facebook Page

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Upload video via URL to Facebook
        run: |
          curl -X POST "https://graph.facebook.com/v24.0/448154571724934/videos" \
            -F "file_url=https://hot.ssplay.net/HY/512171492808394.mp4" \
            -F "published=true" \
            -F "access_token=EAAMBq693DasBQEw5yDk7d6UBhLBKyr8D91tUQnZAVd4qq2iwY80Q7MZCGGBUG41lYCeSRNIi13ZBHt947Jj6DPofXZCs6fMSXZBmXGDZBN2rldDzLsET4VDJO9fEMFrsJaJ06Wmwh8De5hXtlSJFiPDZCjBuzTEkZCaF9h9oUQU3bh9vCGVsBmtWbATGMXkG65FORQZDZD"
